
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(Hmisc)
library(MASS)
library(caret)
library(regclass)
library(ISLR)
library(boot)
library(vcd)
library(pROC)
```

```{r}
data <- read.csv("online_shoppers_intention.csv")
col_names <- names(data)
str(data)
```

We now classify the categorical variable, transfering them into numeric values.
```{r}
data2 <- data[ , 11:18]
# (admin_sd <- sd(data$Administrative))
# admin_avg <- mean(data$Administrative)
# data2$Administrative <- data$Administrative - admin_avg)/admin_sd

data2$Revenue <- ifelse(data2$Revenue == FALSE, 0, 1)
data2$OperatingSystems <- as.factor(data2$OperatingSystems)
data2$Browser <- as.factor(data2$Browser)
data2$Region <- as.factor(data2$Region)
data2$TrafficType <- as.factor(data2$TrafficType)
data2$Weekend <- as.factor(data2$Weekend)
data2$Revenue <- as.factor(data2$Revenue)
```

```{r}
str(data2)
```
```{r}
data3 <- data[ , 1:10]
```


```{r}
reg_data <- cbind(data3, data2)
colnames(reg_data) <- col_names
str(reg_data)
```

```{r}
cor(reg_data[1:10])
```

```{r}
mylogit <- glm(Revenue ~ Administrative + Administrative_Duration + Informational + Informational_Duration + ProductRelated + ProductRelated_Duration + BounceRates + PageValues + SpecialDay + Month + OperatingSystems + Browser + Region + TrafficType + VisitorType + Weekend, data = reg_data, family = binomial(link="logit"))
summary(mylogit)
```

```{r}
unique(data$Month)
```


Now we compute the confidence interval for each coefficient estimate.
```{r}
Confidence=confint(mylogit) 
Confidence
```
Now we compute the odds ratio for each coefficient estimate.
```{r}
#Odds Ratio Calculation, including confidence intervals
oddsr=round(exp(cbind(OddsRatio=coef(mylogit),confint(mylogit))),4)

oddsr
```

First get the TP, TN, FP, and FN, and compute the Accuracy.
```{r}
confmat<-confusion_matrix(mylogit) #Predict True/False Positive/Negative (TP,TN,FP.FN)
confmat
(Accuracy <- (10171  + 745)/12330)
```
```{r}
names(data)
```

```{r}
#first get predicted values
preddata<-with(data,data.frame(reg_data))
probrevenue<-predict(mylogit,newdata=preddata,type="response")
predrevenue<-ifelse(probrevenue > 0.3, 1,0) #at what level should we say prob(default)=1

#Let's determine Accuracy manually first
missclass<-predrevenue!=data$Revenue
misclasserror<-round(mean(predrevenue!=data$Revenue),4)
print(paste('Accuracy',1-misclasserror)) #To determine accuracy manually


```

```{r}
confMat2<-confusionMatrix(data = as.factor(predrevenue),reference = as.factor(reg_data$Revenue), positive = "1")
confMat2 

```










